### PR TITLE
Pagination with page size

### PR DESCRIPTION
**Pull request by Tanvir-rahman**
## What is the Purpose?
Introduced new component for Pagination with page size.

## What was the approach?
Passing page-sizes and page-size props to root component

## Are there any concerns to addressed further before or after merging this PR?
No

## Mentions?
@andrewtpham  @michaelbukachi 

## Issue(s) affected?
No

### CODE REVIEW

**Comment by Tanvir-rahman** [comment]
Hi @ninetteadhikari as far as i know, nope that won't be possible with our current pagination support.For this requirement we need to introduce fully custom pagination(Inside project) and that will take some time.

And as my personal observation -

1) I didn't find that much references with this type of ui in some popular frameworks. That means this is the pretty popular way to traverse (Quasar, Vuetify, Elements, MdBootstrap etc).

2) For initial release i think this will be the ideal way to go. But If we really need that support, it will be best to make custom component inside project with this specific requirement. Might be it won't be possible to support in that way inside component library. Inside project we need some mapping between dropdown and pagination component.

And please let me know what do you think on this?

**Comment by ninetteadhikari** [comment]
> Hi @ninetteadhikari as far as i know, nope that won't be possible with our current pagination support.For this requirement we need to introduce fully custom pagination(Inside project) and that will take some time.
> 
> And as my personal observation -
> 
> 1. I didn't find that much references with this type of ui in some popular frameworks. That means this is the pretty popular way to traverse (Quasar, Vuetify, Elements, MdBootstrap etc).
> 2. For initial release i think this will be the ideal way to go. But If we really need that support, it will be best to make custom component inside project with this specific requirement. Might be it won't be possible to support in that way inside component library. Inside project we need some mapping between dropdown and pagination component.
> 
> And please let me know what do you think on this?

Ah I see, thanks for the clarification 🙂then I think for the first phase we leave it like this and then moving forward as we get more feedback from Katherine on the UI we can think about building something more custom.

**Comment by Tanvir-rahman** [comment]
Hello @ninetteadhikari.
Do i need to follow any more extra step for this PR after your review?

**Comment by ninetteadhikari** [comment]
> Hello @ninetteadhikari.
> Do i need to follow any more extra step for this PR after your review?

this should ok. I'll merge and close it

**Pull request merged**
